version: '3.4'

services:

  arangodb:
    image: arangodb/arangodb
    restart: always
    environment:
      ARANGO_NO_AUTH: 1
    ports:
      -  8529:8529
  cassandra:
    image: cassandra
    restart: always
    ports:
      - 9042:9042
    networks:
      - cassandra
  cqlsh:
     image: nuvo/docker-cqlsh
     restart: always
     links:
       - "cassandra:cassandra"
     environment:
       CQLVERSION: 3.4.5
       QLSH_PORT: 9042
       CQLSH_HOST: cassandra
     networks:
        - cassandra
  couchdb:
    image: couchdb
    restart: always
    environment:
      COUCHDB_USER: root
      COUCHDB_PASSWORD: example
    ports:
      - 5984:5984
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  scylladb:
    image: scylladb/scylla
    restart: always
    ports:
      - 9043:9042

networks:
  cassandra: {}